Revert "ota_from_target_files: Use ro.product.name instead of model"
This reverts commit 490b1046078df75b1115aa19c67902c492a0262b.

It breaks build for Android One Devices, as they don't have a fixed ro.product.name
They get it dynamically from /oem/oem.prop

   ERROR: couldn't find ro.product.name in build.prop
Is the error

import /oem/oem.prop ro.product.name
How they get the prop

Signed-off-by: Akhil Narang <akhil.narang@protonmail.com>